#cloud-config
package_update: true
package_upgrade: true
packages:
  - openssh-server
  - systemd-resolved
  - nftables

users:
  - name: hung
    groups: sudo
    shell: /bin/bash
    sudo: 'ALL=(ALL) NOPASSWD:ALL'
    ssh_authorized_keys:
      - <YOUR_SSH_PUBLIC_KEY>

write_files:
  - path: /etc/systemd/network/10-eth0.network
    content: |
      [Match]
      Name=eth0
      [Network]
      Address=${container_ip}
      Gateway=${gateway_ip}
      DNS=1.1.1.1
      DNS=9.9.9.9
      DNS=8.8.8.8
      DNSDefaultRoute=yes

  - path: /etc/systemd/resolved.conf.d/public-dns.conf
    content: |
      [Resolve]
      DNS=1.1.1.1 9.9.9.9
      FallbackDNS=8.8.8.8 8.8.4.4
      DNSStubListener=yes
      Domains=~.

  - path: /etc/nftables.conf
    content: |
      #!/usr/sbin/nft -f
      flush ruleset

      table inet filter {
        chain input {
          type filter hook input priority filter; policy drop;
          ct state established,related accept
          iif "lo" accept
          meta l4proto { icmp, ipv6-icmp } accept
          tcp dport 22 accept
        }
      }

runcmd:
  - mkdir -p /etc/systemd/resolved.conf.d
  - ln -sf /run/systemd/resolve/stub-resolv.conf /etc/resolv.conf
  - systemctl enable systemd-networkd
  - systemctl start systemd-networkd
  - systemctl enable systemd-resolved
  - systemctl start systemd-resolved
  - systemctl enable nftables
  - systemctl start nftables
  - systemctl enable ssh
  - systemctl start ssh
